apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: send-slack-start
spec:
  extra_vars:
    message: "Le déploiement est commencé sur "
  job_template_name: send-slack
  tower_auth_secret: tower-secret
